### ISSUE TITLE
SplitMerge wrong order

### ISSUE THREAD

**Issue by philfleck** [TES3MP/RakNet#6]
please have a look at this bug - i am still on the original repo and want to switch to yours.
thanks in advance

https://github.com/facebookarchive/RakNet/pull/65

**Comment by Koncord** [comment]
Fixed by https://github.com/TES3MP/RakNet/commit/6226bbbf30ffdc4acb5315a77bbb4f880f3a080e

**Comment by philfleck** [comment]
thx, +1
